import type { Endpoint, WebhookRequest, ResponseRule } from '../types';

export const initialEndpoints: Endpoint[] = [
  {
    id: 'ep-stripe',
    name: 'Thanh toán Stripe',
    slug: 'stripe-webhooks',
    allowed_methods: ['POST'],
    default_status: 200,
    default_headers: {
      'Content-Type': 'application/json',
      'X-Webhook-Provider': 'WebhookLab',
    },
    default_body: JSON.stringify({ received: true, status: 'processed' }, null, 2),
    default_content_type: 'application/json',
    delay_ms: 0,
    error_rate_percent: 0,
    error_status: 500,
    error_body: null,
    redirect_url: null,
    redirect_status: 302,
    auto_forward_url: null,
    forward_response: false,
    is_active: true,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    request_count: 3,
  },
  {
    id: 'ep-github',
    name: 'Sự kiện GitHub CI/CD',
    slug: 'github-events',
    allowed_methods: ['POST', 'GET'],
    default_status: 200,
    default_headers: {
      'Content-Type': 'application/json',
    },
    default_body: JSON.stringify({ ok: true, queued: true }, null, 2),
    default_content_type: 'application/json',
    delay_ms: 150,
    error_rate_percent: 0,
    error_status: 500,
    error_body: null,
    redirect_url: null,
    redirect_status: 302,
    auto_forward_url: null,
    forward_response: false,
    is_active: true,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    request_count: 2,
  },
  {
    id: 'ep-orders',
    name: 'Đơn hàng & Chuyển tiếp (Relay)',
    slug: 'orders',
    allowed_methods: ['POST', 'PUT'],
    default_status: 201,
    default_headers: {
      'Content-Type': 'application/json',
    },
    default_body: JSON.stringify({ id: 'ord_987654', status: 'created' }, null, 2),
    default_content_type: 'application/json',
    delay_ms: 0,
    error_rate_percent: 25,
    error_status: 429,
    error_body: JSON.stringify({ error: 'Quá tải request, vui lòng thử lại sau.', retry_after: 30 }, null, 2),
    redirect_url: null,
    redirect_status: 302,
    auto_forward_url: 'http://localhost:3000/api/orders/webhook',
    forward_response: false,
    is_active: true,
    created_at: new Date(Date.now() - 10800000).toISOString(),
    request_count: 1,
  },
];

export const initialRequests: WebhookRequest[] = [
  {
    id: 'req-001',
    endpoint_id: 'ep-stripe',
    method: 'POST',
    path: '/wh/stripe-webhooks',
    query_params: { env: 'production', v: '2024-04-10' },
    headers: {
      'host': 'localhost:4567',
      'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
      'content-type': 'application/json',
      'stripe-signature': 't=1712750000,v1=9e82bc20173db7e0f8c37d6e812d8',
      'x-request-id': 'req_live_stripe_99212a',
      'accept': '*/*',
    },
    body: JSON.stringify(
      {
        id: 'evt_1Nxxxxxxxxxxxxxxxxxxxxxx',
        object: 'event',
        api_version: '2024-04-10',
        created: 1712750000,
        type: 'payment_intent.succeeded',
        data: {
          object: {
            id: 'pi_3MtwBwLkdIwHu7ix28a3tqPa',
            object: 'payment_intent',
            amount: 890000,
            currency: 'vnd',
            customer: 'cus_99abcz',
            status: 'succeeded',
            payment_method_types: ['card'],
          },
        },
      },
      null,
      2
    ),
    content_type: 'application/json',
    ip_address: '54.187.174.169',
    timestamp: new Date(Date.now() - 45000).toISOString(),
    response_status: 200,
    response_time_ms: 12,
    matched_rule_id: 'rule-stripe-intent',
    matched_rule_name: 'Thanh toán thành công',
    is_simulated_error: false,
  },
  {
    id: 'req-002',
    endpoint_id: 'ep-stripe',
    method: 'POST',
    path: '/wh/stripe-webhooks',
    query_params: {},
    headers: {
      'host': 'localhost:4567',
      'user-agent': 'Stripe/1.0 (+https://stripe.com/docs/webhooks)',
      'content-type': 'application/json',
      'stripe-signature': 't=1712750040,v1=4a821e20173db7e0f8c37d6e812d8',
      'x-request-id': 'req_live_stripe_99213b',
    },
    body: JSON.stringify(
      {
        id: 'evt_1Nyyyyyyyyyyyyyyyyyyyyyy',
        object: 'event',
        api_version: '2024-04-10',
        created: 1712750040,
        type: 'customer.subscription.deleted',
        data: {
          object: {
            id: 'sub_1Oqxyz',
            customer: 'cus_8899aa',
            status: 'canceled',
          },
        },
      },
      null,
      2
    ),
    content_type: 'application/json',
    ip_address: '54.187.205.235',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    response_status: 200,
    response_time_ms: 8,
    is_simulated_error: false,
  },
  {
    id: 'req-003',
    endpoint_id: 'ep-orders',
    method: 'POST',
    path: '/wh/orders',
    query_params: {},
    headers: {
      'host': 'localhost:4567',
      'content-type': 'application/json',
      'user-agent': 'ClientApp/1.0',
    },
    body: JSON.stringify({ item_id: 'prod_99', qty: 2 }, null, 2),
    content_type: 'application/json',
    ip_address: '127.0.0.1',
    timestamp: new Date(Date.now() - 240000).toISOString(),
    response_status: 429,
    response_time_ms: 15,
    matched_rule_id: null,
    matched_rule_name: null,
    is_simulated_error: true,
  },
];

export const initialRules: ResponseRule[] = [
  {
    id: 'rule-stripe-intent',
    endpoint_id: 'ep-stripe',
    name: 'Xác nhận thanh toán thành công',
    priority: 1,
    condition_type: 'json_body',
    condition_field: 'type',
    condition_operator: 'equals',
    condition_value: 'payment_intent.succeeded',
    response_status: 200,
    response_headers: { 'Content-Type': 'application/json' },
    response_body: JSON.stringify({ result: 'receipt_sent', amount_verified: true }, null, 2),
    response_delay_ms: 0,
    is_enabled: true,
  },
  {
    id: 'rule-fail-check',
    endpoint_id: 'ep-stripe',
    name: 'Mô phỏng chữ ký sai (401)',
    priority: 2,
    condition_type: 'header',
    condition_field: 'stripe-signature',
    condition_operator: 'contains',
    condition_value: 'invalid',
    response_status: 401,
    response_headers: { 'Content-Type': 'application/json' },
    response_body: JSON.stringify({ error: 'Chữ ký webhook không hợp lệ' }, null, 2),
    response_delay_ms: 50,
    is_enabled: true,
  },
];
